### ISSUE TITLE
69 warnings with the 0.14.2 compiler

### ISSUE THREAD

**Issue by ntwilson** [purescript-contrib/purescript-formatters#72]
Currently, building master of this library with 0.14.2 yields 69 warnings (mostly from use of `MonadZero` and from unused names).  Would a PR that fixes these warnings be welcome?  If so, for unused names, would it be preferable to prefix with `_` or replace the whole unused name with `_`, or best judgement case-by-case?

**Comment by thomashoneyman** [comment]
Yes! PRs fixing warnings are very much welcome throughout the contrib libraries. For unused names I would generally omit them altogether with _.

**Comment by ntwilson** [comment]
Ugh, I'm sorry I misread the build output, and this library has no warnings, it's all in the dependencies.  I'll close this issue and thank you for the instruction.  I'll focus any effort on the upstream contrib libraries.
